name: Update README

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          sed -i 's#DOWNLOAD_URL_PLACEHOLDER#NEW_DOWNLOAD_URL#g' README.md
          git config --global qiduaoermu "${{ github.actor }}"
          git config --global qiudaoermu@gmail.com "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Update download URL in README" --no-verify
          git push
